#!/bin/bash

_ya() {

 local i cur prev opts cmd
 COMPREPLY=()
 if [[ "${BASH_VERSINFO[0]}" -ge 4 ]]; then
  cur="$2"
 else
  cur="${COMP_WORDS[COMP_CWORD]}"
 fi
 prev="$3"
 cmd=""
 opts=""

 for i in "${COMP_WORDS[@]:0:COMP_CWORD}"; do
  case "${cmd},${i}" in
   ",$1")
    cmd="ya"
    ;;
   ya,emit)
    cmd="ya__subcmd__emit"
    ;;
   ya,emit-to)
    cmd="ya__subcmd__emit__subcmd__to"
    ;;
   ya,exec)
    cmd="ya__subcmd__exec"
    ;;
   ya,help)
    cmd="ya__subcmd__help"
    ;;
   ya,pkg)
    cmd="ya__subcmd__pkg"
    ;;
   ya,pub)
    cmd="ya__subcmd__pub"
    ;;
   ya,pub-to)
    cmd="ya__subcmd__pub__subcmd__to"
    ;;
   ya,sub)
    cmd="ya__subcmd__sub"
    ;;
   ya__subcmd__help,emit)
    cmd="ya__subcmd__help__subcmd__emit"
    ;;
   ya__subcmd__help,emit-to)
    cmd="ya__subcmd__help__subcmd__emit__subcmd__to"
    ;;
   ya__subcmd__help,exec)
    cmd="ya__subcmd__help__subcmd__exec"
    ;;
   ya__subcmd__help,help)
    cmd="ya__subcmd__help__subcmd__help"
    ;;
   ya__subcmd__help,pkg)
    cmd="ya__subcmd__help__subcmd__pkg"
    ;;
   ya__subcmd__help,pub)
    cmd="ya__subcmd__help__subcmd__pub"
    ;;
   ya__subcmd__help,pub-to)
    cmd="ya__subcmd__help__subcmd__pub__subcmd__to"
    ;;
   ya__subcmd__help,sub)
    cmd="ya__subcmd__help__subcmd__sub"
    ;;
   ya__subcmd__help__subcmd__pkg,add)
    cmd="ya__subcmd__help__subcmd__pkg__subcmd__add"
    ;;
   ya__subcmd__help__subcmd__pkg,delete)
    cmd="ya__subcmd__help__subcmd__pkg__subcmd__delete"
    ;;
   ya__subcmd__help__subcmd__pkg,install)
    cmd="ya__subcmd__help__subcmd__pkg__subcmd__install"
    ;;
   ya__subcmd__help__subcmd__pkg,list)
    cmd="ya__subcmd__help__subcmd__pkg__subcmd__list"
    ;;
   ya__subcmd__help__subcmd__pkg,upgrade)
    cmd="ya__subcmd__help__subcmd__pkg__subcmd__upgrade"
    ;;
   ya__subcmd__pkg,add)
    cmd="ya__subcmd__pkg__subcmd__add"
    ;;
   ya__subcmd__pkg,delete)
    cmd="ya__subcmd__pkg__subcmd__delete"
    ;;
   ya__subcmd__pkg,help)
    cmd="ya__subcmd__pkg__subcmd__help"
    ;;
   ya__subcmd__pkg,install)
    cmd="ya__subcmd__pkg__subcmd__install"
    ;;
   ya__subcmd__pkg,list)
    cmd="ya__subcmd__pkg__subcmd__list"
    ;;
   ya__subcmd__pkg,upgrade)
    cmd="ya__subcmd__pkg__subcmd__upgrade"
    ;;
   ya__subcmd__pkg__subcmd__help,add)
    cmd="ya__subcmd__pkg__subcmd__help__subcmd__add"
    ;;
   ya__subcmd__pkg__subcmd__help,delete)
    cmd="ya__subcmd__pkg__subcmd__help__subcmd__delete"
    ;;
   ya__subcmd__pkg__subcmd__help,help)
    cmd="ya__subcmd__pkg__subcmd__help__subcmd__help"
    ;;
   ya__subcmd__pkg__subcmd__help,install)
    cmd="ya__subcmd__pkg__subcmd__help__subcmd__install"
    ;;
   ya__subcmd__pkg__subcmd__help,list)
    cmd="ya__subcmd__pkg__subcmd__help__subcmd__list"
    ;;
   ya__subcmd__pkg__subcmd__help,upgrade)
    cmd="ya__subcmd__pkg__subcmd__help__subcmd__upgrade"
    ;;
   *) ;;
  esac
 done

 case "${cmd}" in
  ya)
   opts="-V -h --version --help emit emit-to exec pkg pub pub-to sub help"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__emit)
   opts="-h --help <NAME> [ARGS]..."
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__emit__subcmd__to)
   opts="-h --help <RECEIVER> <NAME> [ARGS]..."
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__exec)
   opts="-h --help <NAME> [ARGS]..."
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help)
   opts="emit emit-to exec pkg pub pub-to sub help"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__emit)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__emit__subcmd__to)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__exec)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__help)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pkg)
   opts="add delete install list upgrade"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pkg__subcmd__add)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pkg__subcmd__delete)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pkg__subcmd__install)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pkg__subcmd__list)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pkg__subcmd__upgrade)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pub)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__pub__subcmd__to)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__help__subcmd__sub)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg)
   opts="-h --help add delete install list upgrade help"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__add)
   opts="-h --help [IDS]..."
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__delete)
   opts="-h --discard --help [IDS]..."
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help)
   opts="add delete install list upgrade help"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help__subcmd__add)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help__subcmd__delete)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help__subcmd__help)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help__subcmd__install)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help__subcmd__list)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__help__subcmd__upgrade)
   opts=""
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 4 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__install)
   opts="-h --discard --help"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__list)
   opts="-h --help"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pkg__subcmd__upgrade)
   opts="-h --discard --help [IDS]..."
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 3 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pub)
   opts="-h --str --json --list --help <KIND>"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    --str)
     COMPREPLY=($(compgen -f "${cur}"))
     return 0
     ;;
    --json)
     COMPREPLY=($(compgen -f "${cur}"))
     return 0
     ;;
    --list)
     COMPREPLY=($(compgen -f "${cur}"))
     return 0
     ;;
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__pub__subcmd__to)
   opts="-h --str --json --list --help <RECEIVER> <KIND>"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    --str)
     COMPREPLY=($(compgen -f "${cur}"))
     return 0
     ;;
    --json)
     COMPREPLY=($(compgen -f "${cur}"))
     return 0
     ;;
    --list)
     COMPREPLY=($(compgen -f "${cur}"))
     return 0
     ;;
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
  ya__subcmd__sub)
   opts="-h --help <KINDS>"
   if [[ ${cur} == -* || ${COMP_CWORD} -eq 2 ]]; then
    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    return 0
   fi
   case "${prev}" in
    *)
     COMPREPLY=()
     ;;
   esac
   COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
   return 0
   ;;
 esac
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
 complete -F _ya -o nosort -o bashdefault -o default ya
else
 complete -F _ya -o bashdefault -o default ya
fi
