#!/bin/bash

echo -rp "Enter Path to Python App: " appPath

if [[ -f "$appPath" ]]; then
 python -m venv .venv
 source .venv/bin/activate
else
 echo "Not found! Aborting..."
fi

pip install -r requirements.txt
python app.py

echo "To run in a single command..."
echo " uv run app.py"

echo "Or run it globally"
echo " pipx install ."
