#!/bin/bash

# Download the tools
wget -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool

# Create the directories to hosue the app
mkdir -p MyBashApp.AppDir
cd MyBashApp.AppDir

# Add busines logic
cat << 'EOF' > AppRun
#!/bin/bash
echo "Hello, World! I am running inside an AppImage."
echo "I am temporarily mounted at: $APPDIR"
echo "---"
read -p "Press Enter to exit..."
EOF

# Make it executable! (Crucial step)
chmod +x AppRun

# Create the desktop app
cat << 'EOF' > mybashapp.desktop
[Desktop Entry]
Name=MyBashApp
Exec=AppRun
Icon=mybashapp
Type=Application
Categories=Utility;
Terminal=true
EOF

# Create a dummy icon
echo '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><circle cx="32" cy="32" r="32" fill="blue"/></svg>' > mybashapp.svg

# Run the app image
./MyBashApp-x86_64.AppImage
