#!/bin/bash

# Fail & Bail
set -euo pipefail

# global constants
DEV_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# system resource directories
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.local/cache}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

# literal bash export command names
DEV_HOME_EXPORT="DEV_HOME"
USER_BASHRC="${HOME}/.bashrc"

# Colors for logging
GREEN='\e[92m'
BLUE='\e[34m'
PURPLE='\e[35m'
YELLOW='\e[93m'
RED='\e[91m'
GRAY='\e[90m'
WHITE='\e[97m'
END='\e[0m'

WARN="(${YELLOW}*${END})"
INFO="(${WHITE}i${END})"
ERROR="(${RED}!${END})"
QESTN="(${BLUE}?${END})"

declare -A RESOURCE_PATH

# resource source definitions
RESOURCE_PATH["OS_RESOURCES"]="${DEV_HOME}/resources/os"
RESOURCE_PATH["DEV_SOFTWARE"]="${DEV_HOME}/resources/software"
RESOURCE_PATH["SETTINGS_MANAGER"]="${RESOURCE_PATH[OS_RESOURCES]}/recovery/gsettings"
RESOURCE_PATH["SOFTWARE_MANAGER"]="${RESOURCE_PATH[OS_RESOURCES]}/recovery/software"
RESOURCE_PATH["CUSTOM_RESOURCES"]="${RESOURCE_PATH[OS_RESOURCES]}/updates"
RESOURCE_PATH["CUSTOM_SOFTWARE"]="${RESOURCE_PATH[CUSTOM_RESOURCES]}/software"

# Resources exporting to $HOME/.local/share
RESOURCE_PATH["PROFILE_DIR"]="${RESOURCE_PATH[CUSTOM_RESOURCES]}/images/profiles"
RESOURCE_PATH["PROFILE_SRC"]="${RESOURCE_PATH[PROFILE_DIR]}/payload.tar"
RESOURCE_PATH["PROFILE_DST"]="${DATA_HOME}/images"

RESOURCE_PATH["FONT_DIR"]="${RESOURCE_PATH[CUSTOM_RESOURCES]}/fonts"
RESOURCE_PATH["FONT_SRC"]="${RESOURCE_PATH[FONT_DIR]}/payload.tar"
RESOURCE_PATH["FONT_DST"]="${DATA_HOME}/fonts"

RESOURCE_PATH["AUDIO_DIR"]="${RESOURCE_PATH[CUSTOM_RESOURCES]}/audio"
RESOURCE_PATH["AUDIO_SRC"]="${RESOURCE_PATH[AUDIO_DIR]}/payload.tar"
RESOURCE_PATH["AUDIO_DST"]="${DATA_HOME}/audio"

# Resources exporting to $HOME/.config
RESOURCE_PATH["VIM_DIR"]="${RESOURCE_PATH[CUSTOM_SOFTWARE]}/vim"
RESOURCE_PATH["VIM_SRC"]="${RESOURCE_PATH[VIM_DIR]}/vim"
RESOURCE_PATH["VIM_DST"]="${CONFIG_HOME}/vim"

RESOURCE_PATH["TMUX_DIR"]="${RESOURCE_PATH[CUSTOM_SOFTWARE]}/tmux"
RESOURCE_PATH["TMUX_SRC"]="${RESOURCE_PATH[TMUX_DIR]}/tmux"
RESOURCE_PATH["TMUX_DST"]="${CONFIG_HOME}/tmux"

RESOURCE_PATH["KITTY_DIR"]="${RESOURCE_PATH[CUSTOM_SOFTWARE]}/kitty"
RESOURCE_PATH["KITTY_SRC"]="${RESOURCE_PATH[KITTY_DIR]}/kitty"
RESOURCE_PATH["KITTY_DST"]="${CONFIG_HOME}/kitty"

# Resources exportinng to $HOME directory
RESOURCE_PATH["BASH_DIR"]="${RESOURCE_PATH[CUSTOM_SOFTWARE]}/bash"
RESOURCE_PATH["BASH_SRC"]="${RESOURCE_PATH[BASH_DIR]}/bash"
RESOURCE_PATH["BASH_DST"]="${HOME}"

# ==========================================
# Utility Functions
# ==========================================

preflight_check() {

 # Ensure sudo permissions upfront to prevent timeout
 sudo -v

 echo
 echo -e "Checking referential integrity..."
 echo

 local missing=()

 for RESOURCE in "${!RESOURCE_PATH[@]}"; do
  if [[ ! -e "${RESOURCE_PATH[$RESOURCE]}" ]]; then

   echo -e "$ERROR Resource not found: ${YELLOW}$RESOURCE${END}=${WHITE}${RESOURCE_PATH[$RESOURCE]}${END}"
   missing+=("$RESOURCE")
  fi
 done

 read -r -p "Attempt to locate and update references? (y/n) : " answer
 if [[ "$answer" == "y" ]]; then

 #TODO
 echo -e "$WARN TODO...."
 

 else
  echo -e "$ERROR Referential integrity failed. Aborting action..."
  exit 1
 fi

 # Find any broken links
 readarray -t broken_links < <(find . -xtype l)

 if ((${#broken_links[@]} != 0)); then

  RED=$'\e[91m'
  PURPLE=$'\e[95m'
  END=$'\e[0m'

  echo
  echo -e "$ERROR Resolve broken links before proceeding"
  echo -e "${GRAY}"
  find . -xtype l -printf "${RED}%p${END} -> ${PURPLE}%l${END}\n"
  echo -e "${END}"

  # Invoke function to attemp to locate and fix
  source /home/xxx/dev.environment/resources/utils/bash-support/fix-broken-symlinks
  fix-links --base-directory "$DEV_HOME"

 fi

 echo
 echo -e "${GRAY}Initializing Dev Environment${END}"
 echo
}

# ==========================================
# Main Execution
# ==========================================

main() {

 preflight_check

 read -r -p "Restore profile images? [y/N]: " input
 if [[ "${input,,}" =~ ^(y|yes)$ ]]; then
  echo "Restoring profile images..."
  "${RESOURCE_PATH[PROFILE_DIR]}/load-resources" \
   --source "${RESOURCE_PATH[PROFILE_SRC]}" \
   --destination "${RESOURCE_PATH[PROFILE_DST]}"
 else
  echo "Skipping profile"
 fi

 echo -e "${INFO} Installing Font resources..."
 "${RESOURCE_PATH[FONT_DIR]}/load-resources" \
  --source "${RESOURCE_PATH[FONT_SRC]}" \
  --destination "${RESOURCE_PATH[FONT_DST]}"

 echo -e "${INFO} Installing Audio resources..."
 "${RESOURCE_PATH[AUDIO_DIR]}/load-resources" \
  --source "${RESOURCE_PATH[AUDIO_SRC]}" \
  --destination "${RESOURCE_PATH[AUDIO_DST]}"

 read -r -p "Restore previoulsy installed APT packages? [y/N]: " input
 if [[ "${input,,}" =~ ^(y|yes)$ ]]; then
  echo "Restoring previously installed APT packages..."
  "${RESOURCE_PATH[BASH_SRC]}/packages"
 else
  echo "Skipping apt package installs"
 fi

 echo -e "${INFO} Installing Vim resources..."
 "${RESOURCE_PATH[VIM_DIR]}/load-resources" \
  --source "${RESOURCE_PATH[VIM_SRC]}" \
  --destination "${RESOURCE_PATH[VIM_DST]}"

 echo -e "${INFO} Installing Tmux resources..."
 "${RESOURCE_PATH[TMUX_DIR]}/load-resources" \
  --source "${RESOURCE_PATH[TMUX_SRC]}" \
  --destination "${RESOURCE_PATH[TMUX_DST]}"

 echo -e "${INFO} Installing Kitty resources..."
 "${RESOURCE_PATH[KITTY_DIR]}/load-resources" \
  --source "${RESOURCE_PATH[KITTY_SRC]}" \
  --destination "${RESOURCE_PATH[KITTY_DST]}"

 echo -e "${INFO} Installing Bash resources..."
 "${RESOURCE_PATH[BASH_DIR]}/load-resources" \
  --source "${RESOURCE_PATH[BASH_SRC]}" \
  --destination "${RESOURCE_PATH[BASH_DST]}"

 read -r -p "Restore previous environment settings? [y/N]: " input
 if [[ "${input,,}" =~ ^(y|yes)$ ]]; then
  echo "Restoring previously set environment settings..."
  "${RESOURCE_PATH[SETTINGS_MANAGER]}/gsettings-manager" --restore
 else
  echo "Skipped restoring environment settings"
 fi

 read -r -p "Restore previous installed software? [y/N]: " input
 if [[ "${input,,}" =~ ^(y|yes)$ ]]; then
  echo "Restoring previously installed software..."
  "${RESOURCE_PATH[SOFTWARE_MANAGER]}/software-manager" --restore
 else
  echo "Skipped installing software..."
 fi

 echo -e "Reloading shell configuration..."
 source "${USER_BASHRC}" || true

 echo
 echo -e "${GRAY}Setup Complete!${END}"
 echo
 echo -e "${WHITE}⚠️  Restart Terminal ⚠️ ${END}"
 echo
}

main "$@"
