#!/bin/bash

# Fail & Bail
set -e

# System designated directories
SCRIPT_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_HOME="$(cd "${SCRIPT_HOME}/../../.." && pwd)"

# Specific resource being installed
RESOURCE="bash"

# Specific resource paths
SOURCE_PATH="${DEV_HOME}/resources/software/bash"
DESTINATION="${HOME}"

# literal bash export variable names
DEV_EXPORT="DEV_HOME"
BASH_EXPORT="BASH_HOME"

BASHRC_PATH="$HOME/.bashrc"

function find-dev-home {

 local directory_name="dev.environment"

 if [[ -z "$directory_name" ]]; then
  echo "Error: Please provide a directory name to search for." >&2
  echo "Usage: find_user_dir <directory_name>" >&2
  return 1
 fi

 echo "Scanning $HOME for directory: '$directory_name'..."

 find "$HOME" -type d -name "$directory_name" 2>/dev/null
}

function process-payload {

 # Check if 'DEV_HOME' exists in bashrc; if not then create
 if ! grep "${DEV_EXPORT}" "${BASHRC_PATH}" >/dev/null 2>&1; then
  echo "Adding ${DEV_EXPORT} export to ${BASHRC_PATH}"
  {
   echo
   echo "# Path to dev.environment directory"
   echo "${DEV_EXPORT}=\"${DEV_HOME}\""
  } >>"${BASHRC_PATH}"
 fi

 # Check if 'BASH_HOME' exists in bashrc; if not then create
 if ! grep "${BASH_EXPORT}" "${BASHRC_PATH}" >/dev/null 2>&1; then
  echo "Adding ${BASH_EXPORT} export to ${BASHRC_PATH}"
  {
   echo
   echo "# Path to bash resource home directory"
   echo "${BASH_EXPORT}=\"${SOURCE_PATH}\""
  } >>"${BASHRC_PATH}"
 fi

 # Add sourcing of custom dotfiles to .bashrc
 declare -a ACTUAL_NAMES=(".bash_aliases" ".bash_functions" ".bash_completions")

 for NAME in "${ACTUAL_NAMES[@]}"; do
  
  local CONVERTED="${DESTINATION}/${NAME}"

  if ! grep "source ${CONVERTED}" "${BASHRC_PATH}" >/dev/null 2>&1; then
   echo "Adding source entry ${CONVERTED} to bashrc"
   {
    echo "# path to dev defined resource ${CONVERTED}"
    echo "source ${CONVERTED}"
   } >>"${BASHRC_PATH}"
  fi
 done
}

function link-resource {

 local source_file="$1"
 local destination_file="$2"

 local destination_filename=$(basename "$destination_file")
 local destination_path=$(dirname "$destination_file")

 # If any previous exist then remove it (Fixed typos here)
 if [[ -e "$destination_file" || -L "$destination_file" ]]; then
  echo -e "Unlinking existing \e[1;27m$destination_filename\e[0m"
  rm -rf "$destination_file"
 fi

 ln -s "$source_file" "$destination_file"
 echo "Linked: $destination_file -> $source_file"
}

function install-logic {

 echo "Installing ${RESOURCE}..."

 # Map and link accessory bash files
 declare -A BASH_CONFIG_MAPPER

 BASH_CONFIG_MAPPER["aliases"]=".bash_aliases"
 BASH_CONFIG_MAPPER["functions"]=".bash_functions"
 BASH_CONFIG_MAPPER["completions"]=".bash_completions"
 BASH_CONFIG_MAPPER["bashrc"]=".bashrc"

 for CONVERTED in "${!BASH_CONFIG_MAPPER[@]}"; do

  local SRC_FILE="${SOURCE_PATH}/${CONVERTED}"
  local DST_FILE="${DESTINATION}/${BASH_CONFIG_MAPPER[$CONVERTED]}"

  if [[ ! -f "${SRC_FILE}" ]]; then
   echo "Error: Failure referencing source file: ${SRC_FILE}"
   exit 1
  fi

  link-resource "${SRC_FILE}" "${DST_FILE}"
 done

 process-payload

 echo "${RESOURCE} updated!"
 echo
}

function process-arguments {

 while [[ $# -gt 0 ]]; do
  case "$1" in
   -s | --source)
    SOURCE_PATH="$2"
    shift 2
    ;;
   -d | --destination)
    DESTINATION="$2"
    shift 2
    ;;
   -h | --help)
    echo "Usage: load-resources [-s|--source <path>] [-d|--destination <path>]"
    return 0
    ;;
   -*)
    echo "Error: Unknown option $1" >&2
    return 1
    ;;
   *)
    echo "Ignoring positional argument: $1"
    shift 1
    ;;
  esac
 done
}

function main {

 if [[ "$#" -gt 0 ]]; then
  process-arguments "$@"
 fi

 install-logic
}

main "$@"
