#!/bin/bash

BCRYPT_HASH=$(htpasswd -nbBC 10 admin admin | cut -d: -f2)
echo "Kargo (bcrypted-hash) password: $BCRYPT_HASH"

# Update the Kargo secret
kubectl patch secret kargo-api -n kargo --type merge \
 -p "{\"data\":{\"ADMIN_ACCOUNT_PASSWORD_HASH\":\"$(echo -n $BCRYPT_HASH | base64)\"}}"

# Restart Kargo API
kubectl rollout restart deployment/kargo-api -n kargo
kubectl rollout status deployment/kargo-api -n kargo --timeout=60s

echo "Secret is now showing password value"
kubectl get secret kargo-api -n kargo \
  -o jsonpath='{.data.ADMIN_ACCOUNT_PASSWORD_HASH}' | base64 -d
