#!/bin/bash

if [[ -f "$1" ]]; then
 if openssl pkey -in "${1}" -passin pass:wrongpassword -noout > /dev/null 2>&1; then
  echo -e "Not protected \e[91m✗\e[0m"
 else
  echo -e "Protected \e[92m✓\e[0m"
 fi
else
 echo -e "\e[93mUsage: pki-check-password-protected <PEM>\e[0m"
fi
