#!/bin/bash

read -erp "Enter path to RSA file: " rsa_path

rsa_dir=$(dirname "$rsa_path")
rsa_file=$(basename "$rsa_path")

(
 cd "${rsa_dir}"
 yes "" | ssh-keygen -p -f "${rsa_file}"
)

echo "Complete!"
