#!/bin/bash

################################################
# AWS FUNCTIONS                                #
################################################

# @tag:fx,aws
function cpdeploy {
 if [[ "$#" -ne 2 ]]; then
  echo "usage : cpdeploy <deploy-name> <namespace>"
  return 1
 fi
 kubectl get deploy "$1" -n "$2" -o yaml >"$1.yaml"
 echo -e "Deployment saved: \e[1;92m$PWD/$1.yaml\e[0m"
}
export -f cpdeploy

# tag:fx,aws
function setk8s {
 local region="us-east-1"
 local clusterName

 # Check if AWS CLI works
 if ! command -v aws &>/dev/null; then
  echo "AWS CLI not found."
  return 1
 fi

 clusterName=$(aws eks list-clusters --region "$region" | jq -r '.clusters[0]')

 if [[ "$clusterName" == "null" ]] || [[ -z "$clusterName" ]]; then
  echo -e "\e[1;33m No clusters are present :: Run terraform to setup\e[0m"
  return 1
 fi

 echo -e "Setting Kube config for region [\e[1;92m$region\e[0m] and cluster [\e[1;92m$clusterName\e[0m]"

 if aws eks update-kubeconfig --region "$region" --name "$clusterName"; then
  echo -e " -> \e[92mKube config is now set for AWS\e[0m"
 else
  echo -e " (!) \e[1;91mkube config failed setting for AWS\e[0m"
 fi
 echo
}

# tag:fx,aws
function awskeys {
 echo "Getting caller identity"
 aws sts get-caller-identity --query Account --output text
 echo
 echo "Getting access-key info"
 aws sts get-access-key-info
 echo
 echo "Listing access-keys"
 aws iam list-access-keys
}

# tag:fx,aws
function gitlogin {
 curl --request GET \
  --url "https://api.github.com/octocat" \
  --header "Authorization: Bearer $GIT_TOKEN" \
  --header "X-GitHub-Api-Version: 2022-11-28"
}
export -f gitlogin

# tag:fx,aws
function awsuser {
 local username
 username=$(aws iam get-user --query 'User.UserName' --output text 2>/dev/null)

 if [[ $? -ne 0 ]]; then
  echo "Unable to retrieve user. Are you logged in?" >&2
  aws login
  aws sts get-caller-identity
 elif [[ "$username" =~ "None" ]]; then
  echo "root"
 else
  echo "$username"
 fi
}
export -f awsuser
