#!/bin/bash

echo "Running lazyDocker installation script"
if ! command -v lazydocker >/dev/null 2>&1; then
 echo "Installing lazydocker..."
 curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
else
 echo "LazyDocker already installed!"
fi
