#!/bin/bash

wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage

chmod +x linuxdeploy-x86_64.AppImage
chmod +x linuxdeploy-plugin-appimage-x86_64.AppImage

echo
echo "Ensure the plugin is in your PATH or current directory"
echo "Usage example:"
echo " linuxdeploy-x86_64.AppImage --appdir Graphite.AppDir --output appimage"
echo
