#!/bin/bash

## Preview default plymouth splash

## Colors
R='\033[1;31m'
B='\033[1;34m'
G='\033[1;32m'

if [[ $EUID -ne 0 ]]; then
 echo "Elevating privileges..."
 exec sudo "$0" "$@"
fi

# duration in seconds, default is 10s
duration=$1

if [ $# -ne 1 ]; then
 duration=10
fi

plymouthd
plymouth --show-splash
for ((I = 0; I < $duration; I++)); do
 plymouth --update=test$I
 sleep 1
done
plymouth quit
