#!/bin/bash

echo "Adding necessary packages to build..."
sudo apt update
sudo apt install build-essential cmake libopencv-dev maven openjdk-26-jdk v4l-utils -y

echo "Creating build directory..."
mkdir build

echo "Adding user to group 'video'"
if ! id -nG | grep -qw "video"; then                                                                                               
 sudo usermod -aG video $USER                                                                                                      
else                                                                                                                               
 echo "user in video group"                                                                                                
fi 

echo "Listing current devices..."
v4l2-ctl --list-devices
