#!/bin/bash

################################################
# ALIASES                                      #
################################################

EZA_FLAGS="--color=always --icons=always --group-directories-first"
DATE_FORMAT='--time-style=+"%b-%d-%Y %I:%M:%S %p"'

if command -v inxi >/dev/null 2>&1; then
 alias deetz='inxi -Fxz'
fi

alias ls="ls --color=always ${DATE_FORMAT}"
alias ll='ls -alF --color=always'
alias la='ls -A --color=always'
alias lh='ls -ld .* --color=always'
alias l='\ls --color=always -CA'

alias dir='dir --color=always'
alias vdir='vdir --color=always'

if command -v eza >/dev/null 2>&1; then
 alias ls="eza -Al --header ${EZA_FLAGS} ${DATE_FORMAT}"
fi

alias t="tmux"
alias v="vim"

if command -v gnome-text-editor >/dev/null 2>&1; then
 alias edit="gnome-text-editor"
fi

if command -v grc >/dev/null 2>&1; then
 alias watch-ports='watch -n 1 -tc "grc --colour=on ss -tulpn"'
 alias show-ports='grc --colour=on ss -tulpn'
fi

alias gr='cd $(git rev-parse --show-toplevel)'

alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'
alias tree='tree -C'

alias kitty='kitty --config=~/.confg/kitty/kitty.conf'
alias tf='terraform'

for batcmd in bat batcat; do
 if command -v "$batcmd" >/dev/null 2>&1; then
  alias bat="$batcmd --style=full"
  break
 fi
done
unset batcmd

alias mk="minikube"

if command -v kubecolor >/dev/null 2>&1; then
 alias k='kubecolor'
else
 alias k="kubectl"
fi

alias current-context="kubectl config current-context"
alias show-contexts="kubectl config get-contexts"

alias dbx="cd $HOME/devbox"
