#!/bin/bash

read -r -p "Split or Join? (s|j) : " input

if [[ "${input}" == "s" ]]; then
  read -erp "Enter File Path: " filePath

  mkdir -p coder-parts
  split -b 50M -d -a 2 "${filePath}" coder-parts/coder-bundle_

  echo "Split complete! Parts saved to ./coder-parts/"
else
  read -erp "Enter Parts Directory: " dirPath
  cat "${dirPath}"/* > coder-bundle.tar

  echo "Join complete! Reassembled into coder-bundle.tar"
fi
