#!/usr/bin/env bash
set -euo pipefail

# Configuration
RELEASE_NAME="argocd"
CHART_REPO="argo"
CHART_URL="https://argoproj.github.io/argo-helm"
CHART_NAME="argo/argo-cd"
NAMESPACE="argocd"
VALUES_FILE="values.yaml"

echo "Ensuring Helm repository '${CHART_REPO}' is added..."
helm repo add "${CHART_REPO}" "${CHART_URL}" >/dev/null 2>&1 || true

echo "Updating Helm repositories..."
helm repo update

if [[ ! -f "${VALUES_FILE}" ]]; then
 echo "❌ Error: Values file '${VALUES_FILE}' not found in $(pwd)"
 exit 1
fi

echo "Deploying/upgrading ${RELEASE_NAME} in namespace ${NAMESPACE}..."
helm upgrade --install "${RELEASE_NAME}" "${CHART_NAME}" \
 --namespace "${NAMESPACE}" \
 --create-namespace \
 --values "${VALUES_FILE}" \
 --wait \
 --timeout 5m

appVersion=$(helm list -n argocd --no-headers | awk '{print $NF}')
chartVersion=$(helm list -n argocd --no-headers | awk '{print $(NF-1)}')

echo
echo -e "ArgoCD Version : \e[92m$appVersion\e[0m"
echo -e "ArgoCD Chart   : \e[92m$chartVersion\e[0m"

username="admin"
password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
domain=$(kubectl get httproute argocd -n argocd -o jsonpath='{.spec.hostnames[0]}')

echo
echo -e "argocd-url : \e[92mhttps://${domain}\e[0m"
echo -e "admin-user : \e[92m$username\e[0m"
echo -e "admin-pass : \e[92m$password\e[0m"

echo
echo "✅ Deployment complete."
echo
