#!/bin/bash

kubectl create namespace traefik \
 --dry-run=client -o yaml | kubectl apply -f -

kubectl create secret generic tls-ca \
 --namespace traefik \
 --from-file="tls.ca"="ca.crt" \
 --dry-run=client -o yaml | kubectl apply -f -
