#!/bin/bash

# Ensure the script is run with root privileges
if [ "$EUID" -ne 0 ]; then
 echo "Error: Please run this script as root or with sudo."
 exit 1
fi

echo "Starting GitLab Runner installation..."
RUNNER_ARCH="amd64"

DOWNLOAD_URL="https://s3.dualstack.us-east-1.amazonaws.com/gitlab-runner-downloads/latest/binaries/gitlab-runner-linux-${RUNNER_ARCH}"

echo "Downloading the latest GitLab Runner binary..."
curl -L --output /usr/local/bin/gitlab-runner "$DOWNLOAD_URL"

if [ "${?}" -ne 0 ]; then
 echo "Error: Failed to download the binary."
 exit 1
else
 echo "Applying execution permissions..."
 chmod +x /usr/local/bin/gitlab-runner
 echo "gitlab-runner successfully installed!"
fi
