#!/bin/bash

minikube start -p coder-shroder \
  --nodes=3 \
  --memory=24576 \
  --cpus=6 \
  --disk-size=200g \
  --driver=docker \
  --container-runtime=containerd \
  --kubernetes-version=v1.35.1 \
  --addons=metrics-server,default-storageclass
