#!/bin/bash

##########################################
#
# CREATES TRUSTED KERNEL MODULE SIGNER
#
##########################################

# fail & bail
set -e

# ensure root action
sudo -v

SIGNER="xxx"

CERT_KEY="${SIGNER}.key"
CERT_PUB="${SIGNER}.pub"
 
TARGET_DIR="/root/module-signing"

function create-signer {

 echo "Ensuring path: ${TARGET_DIR}"
 sudo mkdir -p "${TARGET_DIR}"

 echo "Creating certificate (key) ${CERT_KEY}"
 echo "Creating certificate (pub)  ${CERT_PUB}"

 sudo openssl req -new -x509 \
  -newkey rsa:2048 \
  -keyout "${CERT_KEY}" \
  -outform DER \
  -out "${CERT_PUB}" \
  -nodes \
  -days 36500 \
  -subj "/CN=${SIGNER}/"

 sudo mv "${CERT_KEY}" "${TARGET_DIR}/"
 sudo mv "${CERT_PUB}" "${TARGET_DIR}/"

 echo "Importing to MOK. You will be prompted to create a password."
 sudo mokutil --import "${TARGET_DIR}/${CERT_PUB}"
}

if [[ "$#" -gt 0 ]]; then
 echo -e "\e[33mmodule-authorizer doesn't require arguments...\e[0m"
 echo -e "\e[90mproceeding...\e[0m"
fi

create-signer
