#!/bin/bash

echo "Packaging the chart...."
helm package ./keycloak-stack
sleep 3

echo "Checking the template..."
helm template keycloak-stack ./keycloak-stack-0.1.0.tgz
sleep 3

echo "Installing the packaged chart..."
helm install keycloak-stack ./keycloak-stack-0.1.0.tgz

echo "Uninstalling the packaged chart..."
helm uninstall keycloak-stack

echo
echo "Complete!"
echo
