#!/bin/bash

DOMAIN="xxx.local"

CERT_DIR="certs"
WILDCARD_CRT="${CERT_DIR}/server-wildcard.crt"
WILDCARD_KEY="${CERT_DIR}/server-wildcard.key"
CA_CRT="${CERT_DIR}/ca.crt"

# 1. Create namespace
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

# 2. Apply Custom Certificates
kubectl create configmap argocd-tls-certs-cm -n argocd \
 --from-file="ca.crt"="${CA_CRT}" \
 --dry-run=client -o yaml | kubectl apply -f -

kubectl create secret tls argocd-server-tls -n argocd \
 --cert="${WILDCARD_CRT}" \
 --key="${WILDCARD_KEY}" \
 --dry-run=client -o yaml | kubectl apply -f -

# 3. Add and update the Argo Helm repository
helm repo add argo https://argoproj.github.io/argo-helm
helm repo update

# 4. Install/Upgrade Argo CD via Helm
# This automatically handles CRDs (including ApplicationSet) and standard resources.
helm --install upgrade argocd argo/argo-cd \
 --create-namespace \
 --namespace argocd \
 --set crds.install=true \
 --set crds.keep=true \
 --set applicationSet.enabled=true \
 --set configs.params."server\.insecure"=true \
 -f values.yaml

# 5. Restart deployments to ensure they pick up the custom injected secrets
kubectl rollout restart deployment argocd-server -n argocd
kubectl rollout restart deployment argocd-repo-server -n argocd
