#!/bin/bash

kubectl create secret tls coder-server-tls \
 --namespace coder \
 --cert=tls.crt \
 --key=tls.key

kubectl create secret generic coder-ca-cert \
 --namespace coder \
 --from-file=ca.crt=ca.crt
