#!/bin/bash

WAYDROID_DESKTOP="$HOME/.local/share/applications/waydroid-controller.desktop"

cat << EOF > ${WAYDROID_DESKTOP}
[Desktop Entry]
Name=Waydroid Control Panel
Comment=Manage Waydroid, Window States, and USB
Exec=/home/$USER/waydroid-controller
Icon=waydroid
Terminal=false
Type=Application
Categories=System;Utility;
EOF


