<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>mcp-webfetch</artifactId>
	<version>1.0-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>26</maven.compiler.source>
		<maven.compiler.target>26</maven.compiler.target>
	</properties>

	<dependencies>
		<!-- Javalin for REST/SSE -->
		<dependency>
			<groupId>io.javalin</groupId>
			<artifactId>javalin</artifactId>
			<version>7.2.3</version>
		</dependency>
		<!-- Gson for JSON manipulation -->
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.14.0</version>
			<scope>compile</scope>
		</dependency>
		<!-- Jsoup for HTML to Text conversion -->
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.17.2</version>
		</dependency>
		<!-- Logging -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.0.12</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.playwright</groupId>
			<artifactId>playwright</artifactId>
			<version>1.62.0</version>
		</dependency>
		<!-- Selenium for Headless JS Rendering -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.23.1</version>
        </dependency>

	</dependencies>
</project>