#!/bin/bash

BACKUP_NAME="cluster-backup-$(date +%Y.%m.%d-%H.%M)"
echo "Backup Name: $BACKUP_NAME"

# Use --include-namespaces to target the minio namespace for the backup payload
velero backup create $BACKUP_NAME --wait --include-namespaces minio
