#!/bin/bash

kubectl create namespace traefik \
 --dry-run=client -o yaml | kubectl apply -f -

kubectl create secret tls wildcard-tls \
 --namespace traefik \
 --cert=tls.crt \
 --key=tls.key \
 --dry-run=client -o yaml | kubectl apply -f -
