#!/bin/bash

sudo apt update

sudo apt install qemu-system-x86 \
 libvirt-daemon-system
 libvirt-clients \
 bridge-utils \
 virt-manager

sudo usermod -aG libvirt $USER
sudo usermod -aG kvm $USER

newgrp libvirt
newgrp kvm

kvm-ok
