#!/bin/bash

# Install CustomResourceDefinitions first
kubectl apply --validate=false -f \
 https://github.com/jetstack/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml

# Add the jetstack helm repo
helm repo add jetstack https://charts.jetstack.io
helm repo update

# You have to create the namespace before executing following command
helm install cert-manager \
 --namespace cert-manager \
 --version v1.17.2 jetstack/cert-manager
