#!/bin/bash

name=$(
 kubectl get applications.argoproj.io -n argocd -o jsonpath='{.items[*].metadata.name}' |
  tr ' ' '\n' |
  fzf --prompt='Select ArgoCD Application To Backup: ' \
  --border=rounded \
  --preview='kubectl get applications.argoproj.io {} -n argocd -o wide')

kubectl get application "${name}" -n argocd -o yaml |
 yq 'del(.metadata.resourceVersion, .metadata.uid, .metadata.creationTimestamp, .metadata.generation, .metadata.annotations."kubectl.kubernetes.io/last-applied-configuration", .status)' \
  >"${name}-argocd-backup.yaml"
