#!/bin/bash

if [[ -z "$1" ]]; then
 read -erp "Enter server.crt path: " CRT_FILE
 if [[ ! -f "$CRT_FILE" ]]; then
  echo "File not found"
  exit 1
 else
  openssl x509 -in "$CRT_FILE" -noout -ext subjectAltName
 fi
fi

