#!/bin/bash

# Fail & Bail
set -e

CONTEXT_DIR="$PWD/auth-app"
DOCKER_FILE="$PWD/Dockerfile"

JAR_NAME="auth-app.jar"

REPO_URL="harbor.local"
REPO_PROJECT="/library/"

TAG="auth-app:latest"
IMAGE_NAME="${REPO_URL}${REPO_PROJECT}${TAG}"

# 1. Check if context directory exists
if [[ ! -d "$CONTEXT_DIR" ]]; then
 echo "Error: Context directory not found!"
 echo "(?) -> $CONTEXT_DIR"
 exit 1
fi

# 2. Check if Dockerfile exists
if [[ ! -f "$DOCKER_FILE" ]]; then
 echo "Error: Dockerfile not found!"
 echo "(?) -> Expected it here: $DOCKER_FILE"
 exit 1
fi

# Build and tag the image with the full repository URL so it can be pushed
docker build \
 --build-arg POM_PATH="$CONTEXT_DIR/pom.xml" \
 --build-arg SRC_PATH="$CONTEXT_DIR/src" \
 --build-arg BUILD_TARGET="$CONTEXT_DIR/app/target/$JAR_NAME" \
 --build-arg JAR_NAME="$JAR_NAME" \
 --tag "$IMAGE_NAME" \
 --file "$DOCKER_FILE" "$CONTEXT_DIR"

echo "Logging into local container repository..."
if docker login "$REPO_URL"; then
 echo "Successfully logged in..."
 
 if docker push "$IMAGE_NAME"; then

  read -r -p "Push to minikube? (y/n) : " answer

  if [[ "$answer" == "y" ]]; then
   minikube image load "${IMAGE_NAME}"
  else
   echo "Skipping Minikube..."
  fi

  echo "Pushed tag: ${IMAGE_NAME} successfully!"

 else
  echo "Failed pushing tag..."
 fi
else
 echo "Failed to login to $REPO_URL"
 exit 1
fi


