#!/bin/bash

watch -n 1 "echo '--- SYSCTL PARAMETERS ---' && sysctl vm.swappiness net.core.somaxconn fs.file-max kernel.pid_max 2>/dev/null && echo -e '\n--- SECURITY LIMITS (root) ---' && ulimit -n -u"
