/*
 * Emoji picker for the banner admin page: a button that opens a searchable panel and inserts the chosen emoji
 * into the message or the bold lead-in, at the cursor.
 *
 * No third-party code and nothing from outside this service: the emoji list is one script (emoji-data.js,
 * generated by support/build-emoji-data), fetched from the banner service the first time the panel opens.
 * Emoji are plain text, drawn by the operating system's emoji font. All text is set with textContent.
 */
(function () {
  'use strict';

  var DATA_URL = '/__banner/admin/emoji-data.js';
  var RECENT_KEY = 'coder-banner-emoji-recent';
  var RECENT_MAX = 16;
  var SEARCH_MAX = 240;
  // Announcement favourites, by the name emoji-data.js gives them (looked up there, so a missing one is skipped).
  var QUICK = ['warning', 'police car light', 'check mark button', 'cross mark', 'red exclamation mark', 'information',
    'wrench', 'hammer and wrench', 'alarm clock', 'locked', 'fire', 'party popper', 'rocket'];

  var cfg = null; // { button, panel, fields: {message, title} }
  var data = null;
  var loading = null;
  var built = false;
  var target = 'message'; // which field receives the emoji: the one the admin used last
  var els = {};
  var recents = [];

  function make(tag, className, text) {
    var el = document.createElement(tag);
    if (className) el.className = className;
    if (text !== undefined) el.textContent = text;
    return el;
  }

  function loadData() {
    if (data) return Promise.resolve(data);
    if (!loading) {
      loading = new Promise(function (resolve, reject) {
        var tag = document.createElement('script');
        tag.src = DATA_URL;
        tag.onload = function () {
          if (window.CoderBannerEmoji && window.CoderBannerEmoji.emoji) resolve((data = window.CoderBannerEmoji));
          else reject(new Error('emoji list missing'));
        };
        tag.onerror = function () {
          reject(new Error('emoji list failed to load'));
        };
        document.head.appendChild(tag);
      });
      loading.catch(function () {
        loading = null; // allow another try
      });
    }
    return loading;
  }

  function readRecents() {
    try {
      var saved = JSON.parse(window.localStorage.getItem(RECENT_KEY) || '[]');
      recents = Array.isArray(saved) ? saved.filter(function (s) { return typeof s === 'string'; }).slice(0, RECENT_MAX) : [];
    } catch (e) {
      recents = [];
    }
  }

  function saveRecent(glyph) {
    recents = [glyph].concat(recents.filter(function (g) { return g !== glyph; })).slice(0, RECENT_MAX);
    try {
      window.localStorage.setItem(RECENT_KEY, JSON.stringify(recents));
    } catch (e) {
      /* private mode: recents just last for this visit */
    }
  }

  // ---- building the panel ---------------------------------------------------------------------------
  function emojiButton(row) {
    var b = make('button', 'emoji', row[1]);
    b.type = 'button';
    b.setAttribute('data-e', row[1]);
    b.setAttribute('data-name', row[2]);
    b.setAttribute('aria-label', row[2]);
    b.title = row[2];
    return b;
  }

  function fill(grid, rows) {
    grid.textContent = '';
    var frag = document.createDocumentFragment();
    rows.forEach(function (row) { frag.appendChild(emojiButton(row)); });
    grid.appendChild(frag);
  }

  function section(title, id) {
    var sec = make('section', 'emoji-sec');
    if (id) sec.id = id;
    sec.appendChild(make('h3', 'emoji-h', title));
    var grid = make('div', 'emoji-grid');
    sec.appendChild(grid);
    return { sec: sec, grid: grid };
  }

  function rowFor(glyph) {
    for (var i = 0; i < data.emoji.length; i++) if (data.emoji[i][1] === glyph) return data.emoji[i];
    return [0, glyph, glyph, ''];
  }

  function build() {
    var panel = cfg.panel;
    panel.textContent = '';

    var top = make('div', 'emoji-top');
    els.search = make('input', 'emoji-search');
    els.search.type = 'search';
    els.search.placeholder = 'Search emoji, e.g. warning, fire, rocket';
    els.search.setAttribute('aria-label', 'Search emoji');
    els.search.autocomplete = 'off';
    top.appendChild(els.search);
    var into = make('div', 'emoji-into');
    into.setAttribute('role', 'radiogroup');
    into.setAttribute('aria-label', 'Insert into');
    into.appendChild(make('span', 'emoji-into-label', 'Insert into:'));
    els.radios = {};
    [['message', 'Message'], ['title', 'Bold lead-in']].forEach(function (t) {
      var label = make('label', 'emoji-radio');
      var radio = make('input');
      radio.type = 'radio';
      radio.name = 'emoji-into';
      radio.value = t[0];
      els.radios[t[0]] = radio;
      label.appendChild(radio);
      label.appendChild(make('span', '', t[1]));
      into.appendChild(label);
    });
    top.appendChild(into);
    panel.appendChild(top);

    els.tabs = make('div', 'emoji-tabs');
    panel.appendChild(els.tabs);

    els.scroll = make('div', 'emoji-scroll');
    els.scroll.tabIndex = -1;
    var quick = section('Quick picks');
    var quickRows = QUICK.map(function (name) {
      for (var i = 0; i < data.emoji.length; i++) if (data.emoji[i][2] === name) return data.emoji[i];
      return null;
    }).filter(Boolean);
    fill(quick.grid, quickRows);
    els.scroll.appendChild(quick.sec);
    els.recent = section('Recently used');
    els.scroll.appendChild(els.recent.sec);

    var byGroup = data.groups.map(function () { return []; });
    data.emoji.forEach(function (row) { byGroup[row[0]].push(row); });
    els.sections = [];
    data.groups.forEach(function (name, i) {
      var sec = section(name.charAt(0).toUpperCase() + name.slice(1));
      fill(sec.grid, byGroup[i]);
      els.scroll.appendChild(sec.sec);
      els.sections.push(sec.sec);
      var tab = make('button', 'emoji-tab', byGroup[i].length ? byGroup[i][0][1] : '?');
      tab.type = 'button';
      tab.setAttribute('aria-label', 'Jump to ' + name);
      tab.title = name;
      tab.addEventListener('click', function () {
        els.scroll.scrollTop = sec.sec.offsetTop - els.scroll.offsetTop;
      });
      els.tabs.appendChild(tab);
    });

    els.results = section('Results');
    els.results.sec.hidden = true;
    els.scroll.appendChild(els.results.sec);
    els.none = make('p', 'emoji-none', 'No emoji match your search.');
    els.none.hidden = true;
    els.scroll.appendChild(els.none);
    panel.appendChild(els.scroll);

    var foot = make('div', 'emoji-foot');
    els.name = make('span', 'emoji-name');
    els.name.setAttribute('aria-live', 'polite');
    foot.appendChild(els.name);
    foot.appendChild(make('span', 'emoji-keys', 'Shift-click to add several · Esc to close'));
    panel.appendChild(foot);
    built = true;
    renderRecents();
    syncTarget();
  }

  function renderRecents() {
    fill(els.recent.grid, recents.map(rowFor));
    els.recent.sec.hidden = !recents.length;
  }

  function syncTarget() {
    if (built) els.radios[target].checked = true;
  }

  // ---- searching --------------------------------------------------------------------------------------
  function search() {
    var words = els.search.value.toLowerCase().split(/\s+/).filter(Boolean);
    var searching = words.length > 0;
    els.tabs.hidden = searching;
    els.results.sec.hidden = !searching;
    Array.prototype.forEach.call(els.scroll.children, function (child) {
      if (child !== els.results.sec && child !== els.none) child.hidden = searching || (child === els.recent.sec && !recents.length);
    });
    if (!searching) {
      els.none.hidden = true;
      return;
    }
    // Best matches first: the name is the query, then starts with it, then contains it, then only a keyword does.
    var query = words.join(' ');
    var hits = [];
    data.emoji.forEach(function (row, i) {
      var name = row[2].toLowerCase();
      var haystack = name + ' ' + row[3].toLowerCase();
      if (!words.every(function (w) { return haystack.indexOf(w) !== -1; })) return;
      var rank = name === query ? 0 : name.indexOf(query) === 0 ? 1 : name.indexOf(query) !== -1 ? 2 : 3;
      hits.push({ row: row, key: rank * 10000 + i });
    });
    hits = hits.sort(function (a, b) { return a.key - b.key; }).slice(0, SEARCH_MAX).map(function (h) { return h.row; });
    fill(els.results.grid, hits);
    els.results.sec.hidden = !hits.length;
    els.none.hidden = hits.length > 0;
    els.scroll.scrollTop = 0;
  }

  // ---- inserting ----------------------------------------------------------------------------------------
  function say(text) {
    els.name.textContent = text;
  }

  // Inserts at the cursor with a space on each side where one is needed, so "⚠️ Impending restart! ⚠️" needs no
  // fiddling. Returns false (and says why) when it would not fit the field's limit.
  function insert(glyph) {
    var field = cfg.fields[target];
    var max = Number(field.getAttribute('maxlength')) || Infinity;
    var start = typeof field.selectionStart === 'number' ? field.selectionStart : field.value.length;
    var end = typeof field.selectionEnd === 'number' ? field.selectionEnd : start;
    var before = field.value.slice(0, start);
    var after = field.value.slice(end);
    var add = (before && !/\s$/.test(before) ? ' ' : '') + glyph + (/^\s/.test(after) ? '' : ' ');
    if (before.length + add.length + after.length > max) {
      say('Not added: the ' + (target === 'title' ? 'bold lead-in' : 'message') + ' would be over its ' + max + ' character limit.');
      return false;
    }
    field.value = before + add + after;
    var caret = (before + add).length;
    field.setSelectionRange(caret, caret);
    field.dispatchEvent(new Event('input', { bubbles: true })); // the admin page refreshes its preview and "unpublished" state
    saveRecent(glyph);
    renderRecents();
    return true;
  }

  // ---- open / close / keyboard -----------------------------------------------------------------------------
  function isOpen() {
    return !cfg.panel.hidden;
  }

  function close(returnFocus) {
    if (!isOpen()) return;
    cfg.panel.hidden = true;
    cfg.button.setAttribute('aria-expanded', 'false');
    if (returnFocus) cfg.button.focus();
  }

  function open() {
    // Normally the last field you focused (tracked below); if the cursor is in one right now, that is the one.
    var active = document.activeElement;
    if (active === cfg.fields.message) target = 'message';
    else if (active === cfg.fields.title) target = 'title';
    syncTarget();
    cfg.button.setAttribute('aria-expanded', 'true');
    cfg.panel.hidden = false;
    if (built) {
      els.search.focus();
      return;
    }
    cfg.panel.textContent = 'Loading emoji…';
    loadData().then(
      function () {
        if (!built) build();
        if (isOpen()) els.search.focus();
      },
      function (e) {
        cfg.panel.textContent = 'Could not load the emoji list (' + e.message + '). Check that you are still signed in, then try again.';
      }
    );
  }

  function visibleEmoji() {
    return Array.prototype.filter.call(cfg.panel.querySelectorAll('.emoji'), function (b) {
      return b.offsetParent !== null;
    });
  }

  // Arrow keys move between emoji by position on screen (rows differ in length between sections).
  function move(from, key) {
    var list = visibleEmoji();
    var i = list.indexOf(from);
    var next = null;
    if (key === 'ArrowRight') next = list[i + 1];
    else if (key === 'ArrowLeft') next = list[i - 1];
    else {
      var r = from.getBoundingClientRect();
      var down = key === 'ArrowDown';
      var best = Infinity;
      list.forEach(function (b) {
        var q = b.getBoundingClientRect();
        var dy = down ? q.top - r.top : r.top - q.top;
        if (dy < 4) return;
        var score = dy * 1000 + Math.abs(q.left - r.left);
        if (score < best) {
          best = score;
          next = b;
        }
      });
    }
    if (next) {
      next.focus();
      next.scrollIntoView({ block: 'nearest' });
    }
  }

  function wire() {
    cfg.button.addEventListener('click', function () {
      if (isOpen()) close(false);
      else open();
    });
    cfg.panel.addEventListener('click', function (e) {
      var b = e.target.closest ? e.target.closest('.emoji') : null;
      if (!b) return;
      if (insert(b.getAttribute('data-e')) && !e.shiftKey) {
        close(false);
        cfg.fields[target].focus();
      }
    });
    cfg.panel.addEventListener('mouseover', function (e) {
      var b = e.target.closest ? e.target.closest('.emoji') : null;
      if (b) say(b.getAttribute('data-name'));
    });
    cfg.panel.addEventListener('focusin', function (e) {
      if (e.target.classList && e.target.classList.contains('emoji')) say(e.target.getAttribute('data-name'));
    });
    cfg.panel.addEventListener('input', function (e) {
      e.stopPropagation(); // typing in the search box is not an edit of the banner
      if (e.target === els.search) search();
    });
    cfg.panel.addEventListener('change', function (e) {
      e.stopPropagation();
      if (e.target.name === 'emoji-into') target = e.target.value;
    });
    cfg.panel.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') {
        e.preventDefault();
        e.stopPropagation();
        close(true);
      } else if (/^Arrow/.test(e.key) && e.target.classList && e.target.classList.contains('emoji')) {
        e.preventDefault();
        move(e.target, e.key);
      } else if (e.key === 'ArrowDown' && e.target === els.search) {
        var first = visibleEmoji()[0];
        if (first) {
          e.preventDefault();
          first.focus();
        }
      }
    });
    document.addEventListener('mousedown', function (e) {
      // Clicking into the message or lead-in (to place the cursor) keeps the panel open; anywhere else closes it.
      var inField = e.target === cfg.fields.message || e.target === cfg.fields.title;
      if (isOpen() && !inField && !cfg.panel.contains(e.target) && !cfg.button.contains(e.target)) close(false);
    });
    document.addEventListener('focusin', function (e) {
      var id = e.target && e.target.id;
      if (id === 'message' || id === 'title') {
        target = id;
        syncTarget();
      }
      if (isOpen() && !cfg.panel.contains(e.target) && !cfg.button.contains(e.target) && id !== 'message' && id !== 'title') close(false);
    });
  }

  window.CoderBannerEmojiPicker = {
    // button: opens the panel; panel: an empty hidden <div>; fields: { message, title } text inputs.
    init: function (options) {
      cfg = options;
      readRecents();
      cfg.panel.hidden = true;
      wire();
    },
  };
})();
