#!/bin/bash

set -x
mkdir -p ./.temp_install

(
 set -euo pipefail

 cd ./.temp_install

 OS="$(uname | tr '[:upper:]' '[:lower:]')"
 ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"
 KREW="krew-${OS}_${ARCH}"

 curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz"
 tar zxvf "${KREW}.tar.gz"

 echo -e "\e[92mInstalling Krew...\e[0m"
 "./${KREW}" install krew
)

read -rp "Delete installation files? (y/n) : " ANSWER
if [[ "$ANSWER" == "y" ]]; then
 rm -rf ./.temp_install
else
 echo "Complete"
fi
