#!/usr/bin/env bash

#fail & bail
set -e

function spinner {
  local message="$1"
  local frames=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
  local delay=0.1
  
  tput civis 
  
  while true; do
    for frame in "${frames[@]}"; do
      printf "\r\e[36m%s\e[0m %s..." "$frame" "$message"
      sleep "$delay"
    done
  done
}

function spinner-message {

 local message="$1"
 shift
 spinner "$message" & 
 local spinner_pid=$!
 trap 'tput cnorm; kill -9 '$spinner_pid' 2>/dev/null; exit 0' INT TERM
 "$@" >/dev/null 2>&1

 local exit_code=$?
 kill "$spinner_pid" 2>/dev/null
 wait "$spinner_pid" 2>/dev/null
 tput cnorm
 if [ $exit_code -eq 0 ]; then
  printf "\r\e[32m✔\e[0m %s completed successfully.\n" "$message"
 else
  printf "\r\e[31m✖\e[0m %s failed (Exit code: %d).\n" "$message" "$exit_code"
 fi
 return $exit_code
}

sudo -v

echo
echo -e "Seraching cluster for active \e[94mHTTPRoutes\e[0m..."
DOMAINS=$(kubectl get httproute -A -o jsonpath='{.items[*].spec.hostnames[*]}' | xargs)

if [[ -z "$DOMAINS" ]]; then
 echo "No HTTPRoutes found. Aborting..."
 exit 1
fi

echo
echo -e "Discovered domains:"

read -ra domains <<<"$DOMAINS"
for domain in "${domains[@]}"; do
 echo -e "✅ \e[92m$domain\e[0m"
done

echo
echo -e "Patching local DNS \e[93m/etc/hosts\e[0m"
echo

for DOMAIN in $DOMAINS; do
 sudo sed -i "/[[:space:]]$DOMAIN\$/d" /etc/hosts
done

echo "127.0.0.1 $DOMAINS" | sudo tee -a /etc/hosts >/dev/null

echo "Local DNS successfully updated ✅" 
echo

echo "Establishing secure tunnel to Traefik Gateway..."
echo -e " \e[93mType Ctrl-C to Quit\e[0m"
echo

export CURRENT_KUBECONFIG=${KUBECONFIG:-$HOME/.kube/config}

TRAEFIK_NAMESPACE="traefik"
HOST_PORT=443
CNTR_PORT=443

# Run in the foreground and let it output directly to your terminal
spinner-message "Tunnel Active..." \
 sudo KUBECONFIG="${CURRENT_KUBECONFIG}" \
 kubectl port-forward \
 --namespace "${TRAEFIK_NAMESPACE}" \
 svc/traefik "${HOST_PORT}":"${CNTR_PORT}"

echo


