#!/bin/bash

kubectl patch configmap argocd-cm -n argocd --type merge -p '{"data": {"exec.enabled": "true"}}'

kubectl patch clusterrole argocd-server --type='json' -p='[{"op": "add", "path": "/rules/-", "value": {"apiGroups": [""], "resources": ["pods/exec"], "verbs": ["create"]}}]'

kubectl patch configmap argocd-rbac-cm -n argocd --type merge -p '{"data": {"policy.csv": "p, role:admin, exec, create, */*, allow"}}'

