[versions]
agp = "9.3.1"
constraintlayout = "2.2.1"
appcompat = "1.7.1"
material = "1.12.0"
preference = "1.2.1"
vertxCore = "5.0.3"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
material = { module = "com.google.android.material:material", version.ref = "material" }
vertx-core = { module = "io.vertx:vertx-core", version.ref = "vertxCore" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertxCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }