#!/bin/bash

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
K9S_HOME="${CONFIG_HOME}/k9s"

mkdir -p "${K9S_HOME}" &>/dev/null

CONTROLLED_RESOURCES=(
 "config.yaml"
 "aliases.yaml"
 "plugins"
 "clusters"
 "skins"
)

# Safe check whether its already on the PATH
if ! command -v symlink-unlink-broken &> /dev/null; then
 /home/xxx/devbox/data/utils/symlink-unlink-broken "${K9S_HOME}"
else
 symlink-unlink-broken "${K9S_HOME}"
fi

for RESOURCE in "${CONTROLLED_RESOURCES[@]}"; do
 ln -sf "$PWD/${RESOURCE}" "${K9S_HOME}/${RESOURCE}"
done
