#!/bin/bash

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
K9S_HOME="${CONFIG_HOME}/k9s"

mkdir -p "${K9S_HOME}" &>/dev/null

CONTROLLED_RESOURCES=(
 "config.yaml"
 "aliases.yaml"
 "plugins"
 "clusters"
 "skins"
)

for RESOURCE in "${CONTROLLED_RESOURCES[@]}"; do
 ln -sf "$PWD/${RESOURCE}" "${K9S_HOME}/${RESOURCE}"
done
