#!/bin/bash

echo "Installing krew"
install-krew
kubectl krew install neat
echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc

echo "Gathering argocd resources..."
RESOURCES=$(kubectl api-resources --namespaced=true --verbs=list -o name | grep -E -v 'applications.argoproj.io|events|endpoints|pods|replicasets' | paste -sd, -)

echo "Dumping argocd resources to file..."
kubectl get $RESOURCES -n argocd -o yaml > argocd-raw.yaml

echo "Minimizing argocd export..."
kubectl neat -f argocd-raw.yaml > argocd-export.yaml

echo "Cleaning up raw export..."
rm argocd-raw.yaml
