// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    iconCache,
    onboarding,
    riverpod,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partitionKey =>
      columnsByName['partition_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i1.DriftAny> get value =>
      columnsByName['value']! as i1.GeneratedColumn<i1.DriftAny>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'PRIMARY KEY NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'partition_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<i1.DriftAny> _column_2(String aliasedName) =>
    i1.GeneratedColumn<i1.DriftAny>(
      'value',
      aliasedName,
      true,
      type: i1.DriftSqlType.any,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get origin =>
      columnsByName['origin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get iconData =>
      columnsByName['icon_data']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get fetchDate =>
      columnsByName['fetch_date']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'PRIMARY KEY NOT NULL',
    );
i1.GeneratedColumn<i2.Uint8List> _column_4(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'icon_data',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetch_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completionDate =>
      columnsByName['completion_date']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completion_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get json =>
      columnsByName['json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get expireAt =>
      columnsByName['expireAt']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get destroyKey =>
      columnsByName['destroyKey']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expireAt',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'destroyKey',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get buttonId =>
      columnsByName['button_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get orderKey =>
      columnsByName['order_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isVisible =>
      columnsByName['is_visible']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get fallbackId =>
      columnsByName['fallback_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'button_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'order_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_visible',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT TRUE',
      defaultValue: const i1.CustomExpression('TRUE'),
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fallback_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'REFERENCES toolbar_button_configs(button_id)ON DELETE SET NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape5 searchTokens = Shape5(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get token =>
      columnsByName['token']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get insertedAt =>
      columnsByName['inserted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get issuerKeyVersion =>
      columnsByName['issuer_key_version']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<i2.Uint8List> _column_16(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'token',
      aliasedName,
      false,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inserted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'issuer_key_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
    idxSearchTokensReservedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape6 searchTokens = Shape6(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
  final i1.Index idxSearchTokensReservedAt = i1.Index(
    'idx_search_tokens_reserved_at',
    'CREATE INDEX idx_search_tokens_reserved_at ON search_tokens (reserved_at)',
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<i2.Uint8List> get token =>
      columnsByName['token']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<int> get insertedAt =>
      columnsByName['inserted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get issuerKeyVersion =>
      columnsByName['issuer_key_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reservedAt =>
      columnsByName['reserved_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reserved_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    proxyProfile,
    idxProxyProfileUpdatedAt,
    proxyRoutingSetting,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
    idxSearchTokensReservedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 proxyProfile = Shape7(
    source: i0.VersionedTable(
      entityName: 'proxy_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProxyProfileUpdatedAt = i1.Index(
    'idx_proxy_profile_updated_at',
    'CREATE INDEX idx_proxy_profile_updated_at ON proxy_profile (updated_at)',
  );
  late final Shape8 proxyRoutingSetting = Shape8(
    source: i0.VersionedTable(
      entityName: 'proxy_routing_setting',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_26, _column_27, _column_28, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape6 searchTokens = Shape6(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
  final i1.Index idxSearchTokensReservedAt = i1.Index(
    'idx_search_tokens_reserved_at',
    'CREATE INDEX idx_search_tokens_reserved_at ON search_tokens (reserved_at)',
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get configJson =>
      columnsByName['config_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'config_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const i1.CustomExpression('CURRENT_TIMESTAMP'),
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT CURRENT_TIMESTAMP',
      defaultValue: const i1.CustomExpression('CURRENT_TIMESTAMP'),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get regularTabsMode =>
      columnsByName['regular_tabs_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get regularTabsProxyConnectionId =>
      columnsByName['regular_tabs_proxy_connection_id']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privateTabsProxyConnectionId =>
      columnsByName['private_tabs_proxy_connection_id']!
          as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY CHECK (id = 1)',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'regular_tabs_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'regular_tabs_proxy_connection_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'private_tabs_proxy_connection_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    proxyProfile,
    idxProxyProfileUpdatedAt,
    proxyRoutingSetting,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
    idxSearchTokensReservedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 proxyProfile = Shape9(
    source: i0.VersionedTable(
      entityName: 'proxy_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_30,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProxyProfileUpdatedAt = i1.Index(
    'idx_proxy_profile_updated_at',
    'CREATE INDEX idx_proxy_profile_updated_at ON proxy_profile (updated_at)',
  );
  late final Shape8 proxyRoutingSetting = Shape8(
    source: i0.VersionedTable(
      entityName: 'proxy_routing_setting',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_26, _column_27, _column_28, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape6 searchTokens = Shape6(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
  final i1.Index idxSearchTokensReservedAt = i1.Index(
    'idx_search_tokens_reserved_at',
    'CREATE INDEX idx_search_tokens_reserved_at ON search_tokens (reserved_at)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get configJson =>
      columnsByName['config_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dnsOverrideJson =>
      columnsByName['dns_override_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dns_override_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    proxyProfile,
    idxProxyProfileUpdatedAt,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
    idxSearchTokensReservedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 proxyProfile = Shape9(
    source: i0.VersionedTable(
      entityName: 'proxy_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_30,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProxyProfileUpdatedAt = i1.Index(
    'idx_proxy_profile_updated_at',
    'CREATE INDEX idx_proxy_profile_updated_at ON proxy_profile (updated_at)',
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape6 searchTokens = Shape6(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
  final i1.Index idxSearchTokensReservedAt = i1.Index(
    'idx_search_tokens_reserved_at',
    'CREATE INDEX idx_search_tokens_reserved_at ON search_tokens (reserved_at)',
  );
}

final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    proxyProfile,
    idxProxyProfileUpdatedAt,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    quickSwitcherButtonConfigs,
    idxQuickSwitcherOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
    idxSearchTokensReservedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 proxyProfile = Shape9(
    source: i0.VersionedTable(
      entityName: 'proxy_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_30,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProxyProfileUpdatedAt = i1.Index(
    'idx_proxy_profile_updated_at',
    'CREATE INDEX idx_proxy_profile_updated_at ON proxy_profile (updated_at)',
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape4 quickSwitcherButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'quick_switcher_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_31, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxQuickSwitcherOrderKey = i1.Index(
    'idx_quick_switcher_order_key',
    'CREATE INDEX idx_quick_switcher_order_key ON quick_switcher_button_configs (order_key)',
  );
  late final Shape6 searchTokens = Shape6(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
  final i1.Index idxSearchTokensReservedAt = i1.Index(
    'idx_search_tokens_reserved_at',
    'CREATE INDEX idx_search_tokens_reserved_at ON search_tokens (reserved_at)',
  );
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_visible',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i1.GeneratedColumn<String> _column_32(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'fallback_id',
  aliasedName,
  true,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'REFERENCES quick_switcher_button_configs(button_id)ON DELETE SET NULL',
);

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    setting,
    proxyProfile,
    idxProxyProfileUpdatedAt,
    iconCache,
    onboarding,
    riverpod,
    toolbarButtonConfigs,
    idxToolbarOrderKey,
    quickSwitcherButtonConfigs,
    idxQuickSwitcherOrderKey,
    searchTokens,
    idxSearchTokensInsertedAt,
    idxSearchTokensReservedAt,
  ];
  late final Shape0 setting = Shape0(
    source: i0.VersionedTable(
      entityName: 'setting',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 proxyProfile = Shape10(
    source: i0.VersionedTable(
      entityName: 'proxy_profile',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_30,
        _column_33,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProxyProfileUpdatedAt = i1.Index(
    'idx_proxy_profile_updated_at',
    'CREATE INDEX idx_proxy_profile_updated_at ON proxy_profile (updated_at)',
  );
  late final Shape1 iconCache = Shape1(
    source: i0.VersionedTable(
      entityName: 'icon_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 onboarding = Shape2(
    source: i0.VersionedTable(
      entityName: 'onboarding',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 riverpod = Shape3(
    source: i0.VersionedTable(
      entityName: 'riverpod',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_8, _column_9, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 toolbarButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'toolbar_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxToolbarOrderKey = i1.Index(
    'idx_toolbar_order_key',
    'CREATE INDEX idx_toolbar_order_key ON toolbar_button_configs (order_key)',
  );
  late final Shape4 quickSwitcherButtonConfigs = Shape4(
    source: i0.VersionedTable(
      entityName: 'quick_switcher_button_configs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_11, _column_12, _column_31, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxQuickSwitcherOrderKey = i1.Index(
    'idx_quick_switcher_order_key',
    'CREATE INDEX idx_quick_switcher_order_key ON quick_switcher_button_configs (order_key)',
  );
  late final Shape6 searchTokens = Shape6(
    source: i0.VersionedTable(
      entityName: 'search_tokens',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_18, _column_19],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxSearchTokensInsertedAt = i1.Index(
    'idx_search_tokens_inserted_at',
    'CREATE INDEX idx_search_tokens_inserted_at ON search_tokens (inserted_at)',
  );
  final i1.Index idxSearchTokensReservedAt = i1.Index(
    'idx_search_tokens_reserved_at',
    'CREATE INDEX idx_search_tokens_reserved_at ON search_tokens (reserved_at)',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get configJson =>
      columnsByName['config_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dnsOverrideJson =>
      columnsByName['dns_override_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get autostart =>
      columnsByName['autostart']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'autostart',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT FALSE',
      defaultValue: const i1.CustomExpression('FALSE'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
    from8To9: from8To9,
    from9To10: from9To10,
  ),
);
