#!/bin/bash

sudo apt install pipx -y

# adds pipx to path
pipx ensurepath

# install globally
sudo pix install --global ruff

# Set the path to the config file
ruff check --config $PWD/ruff.toml

# disable caching
ruff check --no-cache .
ruff format --no-cache .
