#!/bin/bash

echo "Finding Gitlab toolbox pod..."
pod=$(kubectl get pods -lapp=toolbox --namespace gitlab | awk '{print $1}')

if [[ "$?" ]]; then
 echo "Found pod! -> $pod"

 echo "Issuing gitlab-rake command to reset password..."
 kubectl exec -it "$pod" -- gitlab-rake "gitlab:password:reset[root]"
else
 echo "gitlab toolbox pod not found!"
fi
