#org.gradle.java.home=/var/lib/flatpak/app/org.ghidra_sre.Ghidra/x86_64/stable/87718b5091fe9ce604cc5a2ae0cfb80cc9af2ef18ab3c1830e923fae61733194/files/jdk
org.gradle.java.home=/usr/lib/jvm/jdk-26.0.1-oracle-x64
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx9096m -XX:+HeapDumpOnOutOfMemoryError
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE